### PR TITLE
Add functional unit tests

### PR DESCRIPTION
**Pull request by araaliFarooq**
@oxenprogrammer
@eubule
@Takia5
@Leni1
@kizzanaome

### CODE REVIEW

**Comment by kizzanaome** [comment]
Great work @araaliFarooq, Keep it up

**Comment by araaliFarooq** [comment]
Thanks..

**Comment by araaliFarooq** [comment]
wats FTW?

**Comment by araaliFarooq** [comment]
ohh, ok.. hehe.. In sha Allah... n thanx...

On 18 Aug 2018 6:24 pm, "Takia5" <notifications@github.com> wrote:

For The Win

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/araaliFarooq/StackOverflow-lite-api-1/pull/6#issuecomment-414065673>,
or mute the thread

**Pull request merged**
